package com.fota.fotamargin.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table margin_deal_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MarginDealRecordDO implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   合约名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.contract_name
     *
     * @mbg.generated
     */
    private String contractName;

    /**
     * Database Column Remarks:
     *   成交方向(交割方向为持仓反方向) 1-多 2-空 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.direction
     *
     * @mbg.generated
     */
    private Integer direction;

    /**
     * Database Column Remarks:
     *   成交数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   成交价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   手续费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.charge
     *
     * @mbg.generated
     */
    private BigDecimal charge;

    /**
     * Database Column Remarks:
     *   成交类型 1-交割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   成交时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   是否删除。 0 - 否， 1 - 是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.is_valid
     *
     * @mbg.generated
     */
    private Boolean isValid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column margin_deal_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.id
     *
     * @return the value of margin_deal_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.id
     *
     * @param id the value for margin_deal_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.user_id
     *
     * @return the value of margin_deal_record.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.user_id
     *
     * @param userId the value for margin_deal_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.contract_name
     *
     * @return the value of margin_deal_record.contract_name
     *
     * @mbg.generated
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.contract_name
     *
     * @param contractName the value for margin_deal_record.contract_name
     *
     * @mbg.generated
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.direction
     *
     * @return the value of margin_deal_record.direction
     *
     * @mbg.generated
     */
    public Integer getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.direction
     *
     * @param direction the value for margin_deal_record.direction
     *
     * @mbg.generated
     */
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.amount
     *
     * @return the value of margin_deal_record.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.amount
     *
     * @param amount the value for margin_deal_record.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.price
     *
     * @return the value of margin_deal_record.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.price
     *
     * @param price the value for margin_deal_record.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.charge
     *
     * @return the value of margin_deal_record.charge
     *
     * @mbg.generated
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.charge
     *
     * @param charge the value for margin_deal_record.charge
     *
     * @mbg.generated
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.type
     *
     * @return the value of margin_deal_record.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.type
     *
     * @param type the value for margin_deal_record.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.time
     *
     * @return the value of margin_deal_record.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.time
     *
     * @param time the value for margin_deal_record.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.is_valid
     *
     * @return the value of margin_deal_record.is_valid
     *
     * @mbg.generated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.is_valid
     *
     * @param isValid the value for margin_deal_record.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.gmt_create
     *
     * @return the value of margin_deal_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.gmt_create
     *
     * @param gmtCreate the value for margin_deal_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column margin_deal_record.gmt_modified
     *
     * @return the value of margin_deal_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column margin_deal_record.gmt_modified
     *
     * @param gmtModified the value for margin_deal_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MarginDealRecordDO other = (MarginDealRecordDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getContractName() == null ? other.getContractName() == null : this.getContractName().equals(other.getContractName()))
            && (this.getDirection() == null ? other.getDirection() == null : this.getDirection().equals(other.getDirection()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getCharge() == null ? other.getCharge() == null : this.getCharge().equals(other.getCharge()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getContractName() == null) ? 0 : getContractName().hashCode());
        result = prime * result + ((getDirection() == null) ? 0 : getDirection().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getCharge() == null) ? 0 : getCharge().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}