package com.fota.fotamargin.dao.mapper;

import com.fota.fotamargin.dao.domain.MarginDealRecordDO;
import com.fota.fotamargin.dao.domain.MarginDealRecordDOExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MarginDealRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    long countByExample(MarginDealRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int deleteByExample(MarginDealRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int insert(MarginDealRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int insertSelective(MarginDealRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    List<MarginDealRecordDO> selectByExample(MarginDealRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    MarginDealRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarginDealRecordDO record, @Param("example") MarginDealRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarginDealRecordDO record, @Param("example") MarginDealRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarginDealRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table margin_deal_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarginDealRecordDO record);
}